import { createClient } from "@/lib/supabase/server"
import { NextResponse } from "next/server"

export async function POST(request: Request) {
  try {
    const supabase = await createClient()

    const {
      data: { user },
    } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { learner_id, report_type, report_period } = await request.json()

    if (!learner_id || !report_type || !report_period) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 })
    }

    // Get learner and IEP data
    const { data: learner } = await supabase.from("learner_profiles").select("*").eq("id", learner_id).single()

    const { data: ieps } = await supabase.from("ieps").select("*, iep_goals(*)").eq("learner_id", learner_id)

    if (!ieps || ieps.length === 0) {
      return NextResponse.json({ error: "No IEPs found for this learner" }, { status: 404 })
    }

    // Get progress summaries
    const { data: summaries } = await supabase
      .from("progress_summaries")
      .select("*")
      .eq("learner_id", learner_id)
      .order("week_start_date", { ascending: false })
      .limit(report_type === "monthly" ? 4 : 13)

    // Generate report content
    const reportContent = generateReportContent(learner, ieps, summaries, report_type, report_period)

    // Save report to database
    const { data: report, error } = await supabase
      .from("reports")
      .insert({
        learner_id,
        generated_by: user.id,
        report_type,
        report_period,
        content: reportContent,
      })
      .select()
      .single()

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 400 })
    }

    return NextResponse.json(report, { status: 201 })
  } catch (err) {
    console.error(err)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}

function generateReportContent(learner: any, ieps: any[], summaries: any[], reportType: string, period: string) {
  const allGoals = ieps.flatMap((iep) => iep.iep_goals || [])

  const domainStats: Record<string, number> = {}
  allGoals.forEach((goal: any) => {
    if (!domainStats[goal.domain]) {
      domainStats[goal.domain] = 0
    }
    domainStats[goal.domain]++
  })

  const overallProgress =
    summaries.length > 0
      ? summaries.reduce((sum: number, s: any) => {
          const avg = Object.values(s.domain_progress || {}).reduce((a: number, b: any) => a + b, 0)
          return sum + avg / Object.keys(s.domain_progress || {}).length
        }, 0) / summaries.length
      : 0

  return `
ANDA IEP Progress Report
========================
Period: ${period}
Report Type: ${reportType === "monthly" ? "Monthly" : "Quarterly"}

Learner Information:
- Name: ${learner.name}
- Age: ${learner.age}
- Country: ${learner.country}
- Diagnosis Domains: ${Array.isArray(learner.diagnosis_domains) ? learner.diagnosis_domains.join(", ") : "Not specified"}

Summary:
- Active IEPs: ${ieps.length}
- Total Goals: ${allGoals.length}
- Overall Progress: ${overallProgress.toFixed(2)}/5

Domain Breakdown:
${Object.entries(domainStats)
  .map(([domain, count]) => `- ${domain}: ${count} goals`)
  .join("\n")}

Weekly Progress:
${summaries
  .slice(0, reportType === "monthly" ? 4 : 13)
  .map(
    (s: any) => `
Week of ${s.week_start_date}:
${s.summary_text}
Domain Progress: ${Object.entries(s.domain_progress || {})
      .map(([d, p]: [string, any]) => `${d} (${p}/5)`)
      .join(", ")}
  `,
  )
  .join("\n")}

Generated by ANDA NeuroCare
Report generated on ${new Date().toLocaleDateString()}
  `
}
