// Report content/email generation - pure functions extracted from the
// app/api/reports/* route handlers so they can be unit tested without a
// Supabase or Resend connection.

import type { IEP, IEPGoal, LearnerProfile, ProgressSummary, Report } from "@/lib/types/iep"

type IEPWithGoals = IEP & { iep_goals: IEPGoal[] | null }

export function generateReportContent(
  learner: Pick<LearnerProfile, "name" | "age" | "country" | "diagnosis_domains">,
  ieps: IEPWithGoals[],
  summaries: ProgressSummary[],
  reportType: string,
  period: string,
): string {
  const allGoals = ieps.flatMap((iep) => iep.iep_goals || [])

  const domainStats: Record<string, number> = {}
  allGoals.forEach((goal) => {
    const domain = goal.domain || "unspecified"
    domainStats[domain] = (domainStats[domain] || 0) + 1
  })

  const overallProgress =
    summaries.length > 0
      ? summaries.reduce((sum, s) => {
          const values = Object.values(s.domain_progress || {})
          const avg = values.length > 0 ? values.reduce((a, b) => a + b, 0) / values.length : 0
          return sum + avg
        }, 0) / summaries.length
      : 0

  return `
ANDA IEP Progress Report
========================
Period: ${period}
Report Type: ${reportType === "monthly" ? "Monthly" : "Quarterly"}

Learner Information:
- Name: ${learner.name}
- Age: ${learner.age}
- Country: ${learner.country}
- Diagnosis Domains: ${Array.isArray(learner.diagnosis_domains) ? learner.diagnosis_domains.join(", ") : "Not specified"}

Summary:
- Active IEPs: ${ieps.length}
- Total Goals: ${allGoals.length}
- Overall Progress: ${overallProgress.toFixed(2)}/5

Domain Breakdown:
${Object.entries(domainStats)
  .map(([domain, count]) => `- ${domain}: ${count} goals`)
  .join("\n")}

Weekly Progress:
${summaries
  .slice(0, reportType === "monthly" ? 4 : 13)
  .map(
    (s) => `
Week of ${s.week_start_date}:
${s.summary_text}
Domain Progress: ${Object.entries(s.domain_progress || {})
      .map(([d, p]) => `${d} (${p}/5)`)
      .join(", ")}
  `,
  )
  .join("\n")}

Generated by ANDA NeuroCare
Report generated on ${new Date().toLocaleDateString()}
  `
}

export function generateEmailHTML(report: Pick<Report, "content">): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #3C9C87 0%, #0081A7 100%); color: white; padding: 20px; border-radius: 8px; text-align: center; }
        .content { margin: 20px 0; }
        .footer { border-top: 1px solid #ddd; padding-top: 20px; margin-top: 20px; text-align: center; font-size: 12px; color: #999; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>ANDA NeuroCare</h1>
          <p>Progress Report</p>
        </div>
        <div class="content">
          <p>Dear Recipient,</p>
          <p>Please find your ANDA IEP progress report below:</p>
          <pre>${report.content}</pre>
          <p>Best regards,<br>The ANDA Team</p>
        </div>
        <div class="footer">
          <p>&copy; 2025 African Neurodiversity Alliance. All rights reserved.</p>
        </div>
      </div>
    </body>
    </html>
  `
}
